services:
  otsmartlink.core:
    image: otsmartlink.core
    build:
      context: .
      dockerfile: OTSmartLink.Core/Dockerfile
    ports:
      - "5000:5000"  # Example port for the core app, adjust as needed
    restart: always  # Ensures the core app restarts automatically if it crashes

  otsmartlink.agents.opcua:
    image: otsmartlink.agents.opcua
    build:
      context: .
      dockerfile: OTSmartLink.Agents.OPCUA/Dockerfile
    restart: always  # Ensure the agent restarts automatically

  otsmartlink.agents.mqtt:
    image: otsmartlink.agents.mqtt
    build:
      context: .
      dockerfile: OTSmartLink.Agents.MQTT/Dockerfile
    restart: always  # Ensure the agent restarts automatically

  otsmartlink.agents.modbus:
    image: otsmartlink.agents.modbus
    build:
      context: .
      dockerfile: OTSmartLink.Agents.Modbus/Dockerfile
    restart: always  # Ensure the agent restarts automatically

  otsmartlink.services.datastorage:
    image: otsmartlink.services.datastorage
    build:
      context: .
      dockerfile: OTSmartLink.Services.DataStorage/Dockerfile

  otsmartlink.services.monitoring:
    image: otsmartlink.services.monitoring
    build:
      context: .
      dockerfile: OTSmartLink.Services.Monitoring/Dockerfile

  otsmartlink.services.security:
    image: otsmartlink.services.security
    build:
      context: .
      dockerfile: OTSmartLink.Services.Security/Dockerfile
